- hosts: localhost
  become: true
  tasks:
          - name: Add atom apt signing key
            apt_key:
                    url: https://packagecloud.io/AtomEditor/atom/gpgkey
                    state: present

          - name: Add atom repo
            apt_repository:
                    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
                    state: present
                    filename: atom

          - name: Add spotify apt signing key
            apt_key:
                    url: https://download.spotify.com/debian/pubkey.gpg
                    state: present

          - name: Add spotify repo
            apt_repository:
                    repo: deb http://repository.spotify.com stable non-free
                    state: present
                    filename: spotify

          - name: Add sbt apt signing key
            apt_key:
                    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823
                    state: present

          - name: Add sbt repo
            apt_repository:
                    repo: deb https://dl.bintray.com/sbt/debian /
                    state: present
                    filename: sbt

          - name: Install packages
            apt: name={{item}}
            with_items:
                    - vim
                    - flatpak
                    - scala
                    - sbt
                    - gnome-shell-extension-dashtodock
                    - snapd
                    - ibus-mozc
                    - spotify-client
                    - tmux
                    - emacs
                    - chromium
                    - dconf-editor
                    - fonts-noto
                    - materia-gtk-theme
                    - fonts-roboto
                    - adapta-gtk-theme
                    - papirus-icon-theme
                    - atom
