- hosts: localhost
  become: true
  tasks:
          - name: Add atom apt signing key
            apt_key:
                    url: https://packagecloud.io/AtomEditor/atom/gpgkey
                    state: present

          - name: Add atom repo
            apt_repository:
                    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
                    state: present
                    filename: atom

          - name: Add spotify apt signing key
            apt_key:
                    url: https://download.spotify.com/debian/pubkey.gpg
                    state: present

          - name: Add spotify repo
            apt_repository:
                    repo: deb http://repository.spotify.com stable non-free
                    state: present
                    filename: spotify

          - name: Install packages
            apt: name={{item}}
            with_items:
                    - vim
                    - gnome-shell-extension-dashtodock
                    - snapd
                    - ibus-mozc
                    - spotify-client
                    - tmux
                    - emacs
                    - chromium
                    - dconf-editor
                    - fonts-noto
                    - materia-gtk-theme
                    - fonts-roboto
                    - adapta-gtk-theme
                    - papirus-icon-theme
                    - atom
